apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.web.port }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
