import { sql } from 'drizzle-orm';
import {
  bigserial,
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  varchar,
} from 'drizzle-orm/pg-core';

export const task = pgTable(
  'task',
  {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    taskUid: varchar('task_uid', { length: 64 }).notNull().unique('uniq_task_uid'),
    title: varchar('title', { length: 500 }).notNull(),
    titleCopy: varchar('title_copy', { length: 500 }),
    detail: text('detail'),
    taskType: varchar('task_type', { length: 32 }).notNull(),
    priority: varchar('priority', { length: 32 }).notNull(),
    status: varchar('status', { length: 32 }).notNull().default('draft'),
    progressPercent: integer('progress_percent').default(0),
    latestProgress: text('latest_progress'),
    assigneeUserId: varchar('assignee_user_id', { length: 128 }).notNull(),
    assigneeName: varchar('assignee_name', { length: 128 }).notNull(),
    assigneeManagerUserId: varchar('assignee_manager_user_id', { length: 128 }),
    assigneeManagerName: varchar('assignee_manager_name', { length: 128 }),
    assigneeDeptId: varchar('assignee_dept_id', { length: 128 }),
    assigneeDeptName: varchar('assignee_dept_name', { length: 128 }),
    leaderUserId: varchar('leader_user_id', { length: 128 }).notNull(),
    leaderName: varchar('leader_name', { length: 128 }),
    issuerUserId: varchar('issuer_user_id', { length: 128 }).notNull(),
    issuerName: varchar('issuer_name', { length: 128 }),
    assignerUserId: varchar('assigner_user_id', { length: 128 }).notNull(),
    assignerName: varchar('assigner_name', { length: 128 }),
    assignmentType: varchar('assignment_type', { length: 32 }).notNull(),
    collaborators: jsonb('collaborators'),
    startAt: timestamp('start_at', { withTimezone: true }),
    dueAt: timestamp('due_at', { withTimezone: true }).notNull(),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    blockedReason: text('blocked_reason'),
    delayReason: text('delay_reason'),
    daysToDue: integer('days_to_due'),
    isOverdue: boolean('is_overdue').default(false),
    monthBucket: varchar('month_bucket', { length: 7 }).notNull(),
    sourceMonth: varchar('source_month', { length: 7 }),
    isCarriedOver: boolean('is_carried_over').default(false),
    carriedFromTaskUid: varchar('carried_from_task_uid', { length: 64 }),
    carryOverCount: integer('carry_over_count').default(0),
    monthlyCommitmentFlag: boolean('monthly_commitment_flag').default(false),
    bossAttentionFlag: boolean('boss_attention_flag').default(false),
    overdueNotifiedLeaderAt: timestamp('overdue_notified_leader_at', { withTimezone: true }),
    monthlyCloseLocked: boolean('monthly_close_locked').default(false),
    projectUid: varchar('project_uid', { length: 64 }),
    version: integer('version').notNull().default(1),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    createdBy: varchar('created_by', { length: 128 }).notNull(),
    updatedBy: varchar('updated_by', { length: 128 }),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (table) => [
    index('idx_task_assignee_status').on(table.assigneeUserId, table.status),
    index('idx_task_due_at').on(table.dueAt),
    index('idx_task_month_bucket').on(table.monthBucket),
    index('idx_task_leader_user_id').on(table.leaderUserId),
    index('idx_task_boss_attention_flag')
      .on(table.bossAttentionFlag)
      .where(sql`${table.bossAttentionFlag} = true`),
    check('chk_progress_percent', sql`${table.progressPercent} >= 0 AND ${table.progressPercent} <= 100`),
  ],
);
